title: OpenEP
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: blue
header:
  logo_img: images/logo.png
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Examples
      url: /examples
    - label: Roadmap
      url: /roadmap
    - label: Documentation
      url: /documentation
    - label: Engagement
      url: /support
    - label: GitHub
      url: https://github.com/openep/
      primary: true
footer:
  logo_img: images/logo.png
  tagline: The open-source solution for electrophysiology data analysis
  has_nav: true
  nav_title: OpenEP
  nav_links:
    - label: About Us
      url: /about
    - label: GitHub
      url: https://github.com/openep/
  has_social: true
  social_title: Contact Us
  social_links:
    - label: Email
      url: 'mailto:steven.williams@ed.ac.uk'
      new_window: true
  links:
    - label: Cardiac Software Partners
      url: 'https://www.cardiacsoftwarepartners.org'
    - label: Cardiac Electro-Mechanics Research Group
      url: 'http://www.cemrg.co.uk'
  has_subscribe: false

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
  - _gen
